### ISSUE TITLE
Missing dependancies

### ISSUE THREAD

**Issue by sammcj** [avarayr/suaveui#1]
Hey just FYI it looks like the package.json is missing:

- eventsource-parser
- sourcemap

I think the [Vite config](https://vite-pwa-org.netlify.app/guide/faq.html) also might need updating to add some missing compiler includes (e.g. virtual:pwa-register)

**Comment by avarayr** [comment]
Thank you for bringing this up, i've updated the deps.

The virtual:pwa-register bug is quite strange. It seems like Vite correctly imports it (it's readily available in the browser-no errors). Just complaining in the terminal, but aside from that it seems to work fine.. I'll investigate further
