### ISSUE TITLE
Default persona setting

### ISSUE THREAD

**Issue by dmatora** [avarayr/suaveui#11]
Each time you create new chat you have to select a persona, which is really irritating since I only have one persona it it would be really nice if I could be able to set default persona or skip selection if I only have 1 to select

**Comment by dmatora** [comment]
Not exactly same issue, but what about being able to remove obsolete persons?

**Comment by dmatora** [comment]
Just tested creating new dialog.
It's much better not, but it still forces you to do a redundant step.
I believe once you select a person you should be presented with new dialog, not dialog lists.
And it would be Nice if there way a way to skip persona selection entirely (maybe have an option in the settings - single persona mode)

**Comment by avarayr** [comment]
> Just tested creating new dialog. It's much better, but it still forces you to do a redundant step. I believe once you select a person you should be presented with new dialog, not dialogs list. And it would be nice if there way a way to skip persona selection entirely (maybe have an option in the settings - single persona mode)

So I'm assuming you are creating new chats because you want to reset the chat to have a clean conversation?

**Comment by dmatora** [comment]
yes, but no :)
I want to start a separate subject without deleting old one.
