### ISSUE TITLE
Missing timestamps

### ISSUE THREAD

**Issue by dmatora** [avarayr/suaveui#13]
In iMessage I can swipe texts to the left and see each message time.
In suaveui I can't see a way to see timestamps.
Since notifications are mainly designed to see response to your question after significant delay, it would really be helpful to see how much time each particular response took.

**Comment by alrifat2** [comment]
@dmatora I'm working on getting this done. Please check out the PR so you can try it out yourself. It's not 1:1 with iMessage for now but I will be looking further into it to do so. As always, you're welcome to make a PR if you fix it before me! That'll be great for others also interested in this.

**Comment by dmatora** [comment]
I've tried it and while it's obvious improvement, it's still incomplete.
Current implementation breaks mouse text selection on desktops.
iMessage doesn't expect you to swipe on Desktop it allows toggling timestamp in context menu.
I think, for development simplicity, on desktop they could be always on.

**Comment by avarayr** [comment]
> I've tried it and while it's obvious improvement, it's still incomplete. Current implementation breaks mouse text selection on desktops. iMessage doesn't expect you to swipe on Desktop it allows toggling timestamp in context menu. I think, for development simplicity, on desktop they could be always on.

Out of curiosity, in which cases do you *need* to view timestamps while having a text selection at the same time?

**Comment by dmatora** [comment]
Text selection is always broken, including when time is not visible

**Comment by avarayr** [comment]
> Text selection is always broken, including when time is not visible

Good catch, somehow i completely missed that, sorry

**Comment by avarayr** [comment]
> Text selection is always broken, including when time is not visible

I've pushed some changes to master
 
* Desktop screens
	* Dragging to reveal timestamp is disabled 
	* new "Show Times" context menu item is added 
	* Enabled text selection
	* tap-and-hold is disabled 

* Mobile Screens
	* Dragging to reveal time is enabled
	* Text selection is only available when the message is focused (mimics Telegram behavior)

* Text selection in code blocks is always enabled regardless of screen size
