### ISSUE TITLE
Couple of minor UI bugs

### ISSUE THREAD

**Issue by av** [avarayr/suaveui#4]
### Notifications are blocking clicks

1. Ensure you don't have ollama running (or running on a non-standard port)
2. Open LLM configuration screen, click on "Model" select
3. Observe a toast "Failed to fetch models"

##### Expected

Toast disappears after some time, it's possible to interact with the rest of the UI while it's on screen

##### Actual

It's not possible to click anything except the toast while it's shown. The toast stays on indefinitely (or until locak/unlock screen)

### UI state desync with stored config

1. On a fresh install, with Ollama running on a non-standard port, for example: `http://localhost:33821`
2. Configure the UI to use that custom instance
3. Chat with some personas using the configured model
4. Open the LLM configuration screen again

##### Expected

Configuration screen displays expected settings

##### Actual

Configuration screen displays default settings for a selected provider, you can still chat with personas, though

**Comment by avarayr** [comment]
@av Thank you for raising this issue, please validate if the fix works for you

**Comment by av** [comment]
Thank you for taking a look, and for making the fixes!

Just tried it - settings are now correctly restored, but toasts are still blocking the interactions. If it helps, I reproduced it with Chrome's responsive viewport. It starts to reproduce when the settings modal is replaced with a bottom drawer.

**Comment by avarayr** [comment]
> Thank you for taking a look, and for making the fixes!
> 
> Just tried it - settings are now correctly restored, but toasts are still blocking the interactions. If it helps, I reproduced it with Chrome's responsive viewport. It starts to reproduce when the settings modal is replaced with a bottom drawer.

Thanks, looks like I found the issue. The bottom sheet was preventing "click outside" mechanism of the <Select> component, should be fixed now.
